### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by PLUCS2** [tt954/wavetape#2]
- [x] Lets talk about how you will store your genres 
- [x] Add follows

**Comment by tt954** [comment]
I was thinking of storing my genres in a class constant array in the Track model.

**Comment by PLUCS2** [comment]
- [ ] Have genres be an array for tracks (because they can belong to multiple genres) 
- [ ] Add genres to your schema

**Comment by tt954** [comment]
- Checked and a track can only belong to _one_ genre, therefore, did not add a trackgenres joins table. Genre_id added to track sample splice of state.

**Comment by PLUCS2** [comment]
- [ ] Add genres to state - in `entities` so that the `id`s correspond to something
- [ ] Add a `genre_id` onto the `tracks` table in your schema
